//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class Employee
    {
        //[JsonProperty("Id")]
        public string Id { get; set; }
       // [JsonProperty("FirstName")]
        public string FirstName { get; set; }
     //   [JsonProperty("MiddleName")]
        public string MiddleName { get; set; }
      //  [JsonProperty("LastName")]
        public string LastName { get; set; }
       // [JsonProperty("DOB")]
        public Nullable<System.DateTime> DOB { get; set; }
      //  [JsonProperty("Desgination")]
        public string Desgination { get; set; }
     //   [JsonProperty("ManagerId")]
        public string ManagerID { get; set; }
      //  [JsonProperty("Salary")]
        public Nullable<int> Salary { get; set; }
      //  [JsonProperty("TeamID")]
        public string TeamID { get; set; }
     //   [JsonProperty("DOJ")]
        public Nullable<System.DateTime> DOJ { get; set; }
       // [JsonProperty("DOL")]
        public string DOL { get; set; }
    }
   
     
}
